#define BFA_VERSION            "3.2.7.0"
#define BFA_MAJOR              3
#define BFA_MINOR              2
#define BFA_REV                7
#define BFA_PATCH              0
#define BFA_BUILD              sqa
#define BFA_COPYRIGHT_YEAR     "2016"
#define BFA_BLD_TAG            "3.2.7.0"
#define BFA_BLD_DATE           "04/21/2016"
#define BFA_BLD_TIME           "21.37.45"
